services:
  app-server:
    container_name: app-server
    build:
      context: ../                        
      dockerfile: docker/node/Dockerfile      
    working_dir: /usr/src/app             
    volumes:
      - /usr/src/app/                     
    depends_on:
      - mariadb-app 
    networks:
      - app-network                     

  php-server:
    build: ./php
    container_name: php-server
    volumes:
      - ./php/applications/:/var/www/html
    ports:
      - "7070:80"
    networks:
      - app-network
    depends_on:
      - mariadb-php
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  mariadb-php:
    image: mariadb:11.6.2
    container_name: mariadb-php
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - php_db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--password=password"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  mariadb-app:
    image: mariadb:latest   
    container_name: mariadb-app              
    restart: always                       
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   
    volumes:
      - mariadb_data:/var/lib/mysql      
    ports:
      - "3307:3306"                      

  nginx:
    image: nginx:latest                   
    ports:
      - "6672:80"                         
      - "6673:81"                         
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
      - phpmyadmin                        

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest   
    environment:
      PMA_HOST: mariadb                  
      MYSQL_ROOT_PASSWORD: rootpassword   
    depends_on:
      - mariadb-app                           

networks:
  app-network:
    driver: bridge                        

volumes:
  mariadb_data:
  php_db_data:    
