services:
  app-server:
    container_name: app-server
    build:
      context: ../                        
      dockerfile: docker/node/Dockerfile      
    working_dir: /usr/src/app             
    volumes:
      - /usr/src/app/                     
    depends_on:
      - mariadb-app 
    networks:
      - app-network                     

  php-server:
    build: ./php
    container_name: php-server
    volumes:
      - ./app:/var/www/html
    ports:
      - "7273:80"
    depends_on:
      - mariadb-php
    networks:
      - app-network
  
  mariadb-php:
    image: mariadb:latest
    container_name: mariadb-php
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  mariadb-app:
    image: mariadb:latest   
    container_name: mariadb-app              
    restart: always                       
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   
    volumes:
      - mariadb_data:/var/lib/mysql      
    ports:
      - "3307:3306"                      

  nginx:
    image: nginx:latest                   
    ports:
      - "6672:80"                         
      - "6673:81"                         
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
      - phpmyadmin                        

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest   
    environment:
      PMA_HOST: mariadb                  
      MYSQL_ROOT_PASSWORD: rootpassword   
    depends_on:
      - mariadb-app                           

networks:
  app-network:
    driver: bridge                        

volumes:
  mariadb_data:                          
