version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    working_dir: /usr/src/master/app
    volumes:
      - /usr/src/master/
      - ../app:/usr/src/master/app
      - ../docker:/usr/src/master/docker
      - ../.git:/usr/src/master/.git
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306"

  nginx:
    image: nginx:latest
    ports:
      - "6672:80"
      - "6673:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mariadb

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: