version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    working_dir: /usr/src/master/app
    volumes:
      - /usr/src/master/
      - ../app:/usr/src/master/app
      - ../docker:/usr/src/master/docker
      - ../.git:/usr/src/master/.git
    ports:
      - "3000:3000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mariadb

volumes:
  mariadb_data: